server:
  port: 20610
  servlet:
    context-path: /springboot
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
#### 信任所有的包，ActiveMQ传递序列化对象时，防止序列化漏洞
      trust-all: true
    in-memory: false